### ISSUE TITLE
Incorrect fuse bits order for ATTiny2313

### ISSUE THREAD

**Issue by v2e** [lancos/ponyprog#17]
Hello!
The order of the fuse bits in the high fuse byte is incorrect for ATTiny2313.
Here is the fuse bits dialog in Ponyprog:
![ponyprog-fuse2313-wrongorder](https://user-images.githubusercontent.com/2400171/81848516-e3871780-955d-11ea-9899-b0b6c7be1322.png)

And here is the table from the datasheet:
![attiny2313-datasheet-highfuse](https://user-images.githubusercontent.com/2400171/81848551-f6015100-955d-11ea-9be1-5d57a58bb2ad.png)

So as you can see, the bits are in the wrong order in the dialog box. Including the RSTDISBL bit.

And also, is there a way to make the high byte and the low byte visually separated from each other in the interface? It seems to be more convenient to check them against the datasheet this way, and also to distinguish better.
Thank you!

**Comment by eduard-x** [comment]
Hello!
Thanks for information! Спасибо! :)
The description was fixed and pushed in branch ATTiny2313-fuse-fix.
Best regards,
Eduard.
