### ISSUE TITLE
Ponyprog 3.0, CancelIOEx could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by xiaolaba** [lancos/ponyprog#6]
hi,
can you please help to look at this.
for xp is not working.

perhaps this is the issue
https://bugreports.qt.io/browse/QTBUG-58407

**Comment by lancos** [comment]
Hi,
PonyProg3 (Qt5.8) doesn't support WindowsXP. If you need WindowsXP you can build the old PonyProg2 legacy_v2 branch (https://github.com/lancos/ponyprog/tree/legacy_v2) without Qt.

**Comment by xiaolaba** [comment]
thanks you Sir.got it
best regards,xiao

**Comment by eduard-x** [comment]
Hi xiaolaba,
You can build the project for Windows XP with Qt4.8. This is possible, but you must switch the CMakeLists for Qt4: OPTION (USE_QT5 "Using of Qt5 version for compiling" OFF)
Regards,
Eduard

**Comment by xiaolaba** [comment]
hello Eduard
We had a shot with qt-5.7, used migwin-32 for compiling, it is ok with win10 & test, but not yet carry over to XP machine, however, one more question is about the dll dynamic loading but not single exe file. it is something that no easy for user unless copy those DLLs to target machine, looks like qt is no default switch for user to do such extends.
we will try qt4.8 as you have suggested.

best regards,
xiao
