### ISSUE TITLE
some small fixes for spelling and desktop file

### ISSUE THREAD

**Issue by tijuca** [lancos/ponyprog#8]
Hi,

I picked up the  v3.0.0 tag and reworked the source into a Debian package. The package was accepted by the Debian ftpmasters a few hours ago. So if all is going well it will be part of the Buster release in some months.

https://tracker.debian.org/pkg/ponyprog

I added some additional patches to the package, too of them are about fixing some misspelled words, and one is about adding a Keyword entry to the desktop file. Please consider to include these fixes into the source.

https://salsa.debian.org/electronics-team/ponyprog/tree/debian/sid/debian/patches

And Lintian, the main QS tool for packaging in Debian, is mentioning that the Icon for Ponyprog isn't available in a recommended resolution. Is it possible to add a SVG graphic to the source so I can created the various sizes of the icon while packaging? Or add various sizes of the icon to the icons/ folder?

https://appstream.debian.org/sid/main/issues/ponyprog.html

Regards

**Comment by lancos** [comment]
Hi,
thank you for your patches, I applied them to the master branch. I also added SVG icon as suggested.
I'm going to make 3.0.1 tag with these changes.
